#!/usr/bin/env python3
"""
Build script: renders every page of the site from data.

`content.json` (plus the pipeline caches publications_data.json / software_data.json)
is the single source of truth. This script WRITES each page in full — head, nav,
hero/header band, generated content, footer and scripts all come from the PAGES
registry and render_shell() below; the .html files are build output, not templates.
JS only adds interactivity (theme toggle, hero canvas, listview). Idempotent.

Usage: python scripts/build_html.py
"""

import json
import math
import re
import sys
from datetime import date
from pathlib import Path
from urllib.parse import urlparse

# Project root is one level up from scripts/
PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONTENT_JSON = PROJECT_ROOT / "assets" / "data" / "content.json"
PUBLICATIONS_JSON = PROJECT_ROOT / "assets" / "data" / "publications_data.json"
SOFTWARE_JSON = PROJECT_ROOT / "assets" / "data" / "software_data.json"
SITEMAP_XML = PROJECT_ROOT / "sitemap.xml"
FEED_FILE = "feed.xml"
FEED_XML = PROJECT_ROOT / FEED_FILE

# Redesign per-page content generators (scripts/ on path so they import cleanly)
sys.path.insert(0, str(Path(__file__).resolve().parent))
from pages_shared import (SPRITE, attr_esc, card_meta, clean_text, esc,  # noqa: E402
                          esc_text, listview_status, percent_shares, slug,
                          strip_tags, term_month, url_attr, warn)
from pages_talks import generate_content as gen_talks          # noqa: E402
from pages_teaching import generate_content as gen_teaching    # noqa: E402
from pages_mentorship import generate_content as gen_mentorship  # noqa: E402
from pages_awards import generate_content as gen_awards        # noqa: E402
from pages_service import generate_content as gen_service      # noqa: E402
from pages_software import generate_content as gen_software    # noqa: E402
from pages_news import generate_content as gen_news            # noqa: E402

SITE_URL = "https://joshspeagle.com"
SITE_NAME = "Joshua S. Speagle"
OG_IMAGE = "assets/images/og-card.png"
OG_IMAGE_SIZE = (1200, 630)
OG_IMAGE_ALT = "Joshua S. Speagle — Astrostatistics at the University of Toronto"
CV_URL = "https://joshspeagle.com/bio-cv/CV_speagle.pdf"
BIBTEX_PATH = "assets/data/publications.bib"   # generated by scripts/export_bib.py
DEFAULT_FOOTER_NOTE = "Astronomy · Statistics · AI"

# ---------------------------------------------------------------------------
# Page registry — one row per rendered document.
#
#   file       output filename (relative to the project root)
#   nav        nav label (None = not in the nav)
#   title      <title>; None derives "<pages.<key>.title> · Joshua S. Speagle"
#   canonical  path under SITE_URL (None = no canonical/OG block, e.g. 404)
#   layout     'hero' (Home) | 'header' (kicker/title/tagline band) | 'notfound'
#   scripts    assets/js/redesign/*.js loaded after site.js (board.js first)
#   sitemap    <priority> in sitemap.xml (None = excluded)
#   sources    data files whose newest change dates the footer + sitemap lastmod
#   footer     right-hand footer note (defaults to DEFAULT_FOOTER_NOTE)
#   root       URL prefix for in-page links/assets ("" relative, "/" absolute)
# ---------------------------------------------------------------------------
PAGES = {
    "index": dict(file="index.html", nav="Home", title=f"{SITE_NAME} · Astrostatistics",
                  canonical="/", layout="hero", scripts=["board.js", "hero.js"], sitemap="1.0",
                  sources=["content", "publications"], content_key="home"),
    "publications": dict(file="publications.html", nav="Publications", canonical="/publications.html",
                         layout="header", scripts=["board.js", "listview.js", "pubchart.js"], sitemap="0.8",
                         sources=["publications"],
                         footer="Data from SAO/NASA ADS &amp; Google Scholar"),
    # Software dates from its own cache only: the stats it shows are pipeline-owned,
    # so the stamp must not drift forward when unrelated content.json prose changes.
    "software": dict(file="software.html", nav="Software", canonical="/software.html",
                     layout="header", scripts=["board.js", "listview.js"], sitemap="0.6",
                     sources=["software"]),
    "talks": dict(file="talks.html", nav="Talks", canonical="/talks.html",
                  layout="header", scripts=["board.js", "listview.js"], sitemap="0.6", sources=["content"]),
    "teaching": dict(file="teaching.html", nav="Teaching", canonical="/teaching.html",
                     layout="header", scripts=["board.js", "listview.js"], sitemap="0.6", sources=["content"]),
    "mentorship": dict(file="mentorship.html", nav="Mentorship", canonical="/mentorship.html",
                       layout="header", scripts=["board.js", "listview.js"], sitemap="0.8", sources=["content"]),
    "biography": dict(file="biography.html", nav="Biography", canonical="/biography.html",
                      layout="header", scripts=["board.js"], sitemap="0.6", sources=["content"]),
    "news": dict(file="news.html", nav="News", canonical="/news.html",
                 layout="header", scripts=["board.js", "listview.js"], sitemap="0.6", sources=["content"]),
    "awards": dict(file="awards.html", nav="Awards", canonical="/awards.html",
                   layout="header", scripts=["board.js", "listview.js"], sitemap="0.6", sources=["content"]),
    "service": dict(file="service.html", nav="Service", canonical="/service.html",
                    layout="header", scripts=["board.js", "listview.js"], sitemap="0.6", sources=["content"]),
    "404": dict(file="404.html", nav=None, title=f"Page not found · {SITE_NAME}",
                canonical=None, layout="notfound", scripts=["board.js"], sitemap=None,
                sources=["content"], root="/", noindex=True, container="notfound-content",
                content_key="notfound"),
}

# Nav structure: top-level items and dropdown groups. Entries are either a page key
# or an explicit external link. Labels come from PAGES[...]["nav"].
NAV = [
    {"page": "index"},
    {"label": "Research", "items": [{"page": "publications"}, {"page": "software"}, {"page": "talks"}]},
    {"label": "Teaching &amp; Mentoring", "items": [
        {"page": "teaching"}, {"page": "mentorship"},
        {"label": "Group / ART", "url": "https://astrostatuoft.com/"}]},
    {"label": "About", "items": [
        {"page": "biography"}, {"page": "news"}, {"page": "awards"}, {"page": "service"}]},
]

DATA_FILES = {"content": CONTENT_JSON, "publications": PUBLICATIONS_JSON, "software": SOFTWARE_JSON}


class BuildError(RuntimeError):
    """A page could not be rendered (bad or missing data file)."""


def page_meta(data, key):
    """The pages.<key> block in content.json for a registry page (Home lives at
    pages.home, everything else at pages.<page key>)."""
    return (data.get("pages", {}) or {}).get(PAGES[key].get("content_key", key)) or {}


def container_id(key):
    """Id of the element a page's generated content is written into. Home is the
    exception: it has four generated sections instead of one container."""
    return PAGES[key].get("container", f"{key}-content")


# ---------------------------------------------------------------------------
# Data freshness (footer "Updated <Month Year>" + sitemap lastmod)
#
# Every date on the site is READ FROM THE DATA, never from the clock or from git:
# each data file declares when it was last updated, so rebuilding the site from the
# repository alone is byte-identical no matter which day it runs (the CI staleness
# gate diffs the committed build against a rebuild). The publication and software
# caches own their own timestamps (their fetch scripts write them); content.json
# carries site.lastUpdated, bumped by whoever edits it.
# ---------------------------------------------------------------------------

# data key -> dotted paths to try, in order, for that file's freshness date
_DATE_FIELDS = {
    "content": ("site.lastUpdated",),
    "publications": ("metrics.lastUpdated", "lastUpdated"),
    "software": ("lastUpdated", "lastFetched"),
}

_JSON_CACHE = {}
_DATE_CACHE = {}


def load_data_file(key):
    """Parsed contents of one registered data file ({} when it cannot be read)."""
    if key not in _JSON_CACHE:
        try:
            _JSON_CACHE[key] = json.loads(DATA_FILES[key].read_text(encoding="utf-8"))
        except (OSError, ValueError) as err:
            warn(f"cannot read {DATA_FILES[key].name}: {err}")
            _JSON_CACHE[key] = {}
    return _JSON_CACHE[key]


def _dig(blob, path):
    """Look up a dotted path in nested dicts; None when any step is missing."""
    for part in path.split("."):
        if not isinstance(blob, dict):
            return None
        blob = blob.get(part)
    return blob


def data_date(key):
    """The update date a data file declares for itself, or None if it declares none."""
    if key not in _DATE_CACHE:
        found = None
        for field in _DATE_FIELDS[key]:
            try:
                found = date.fromisoformat(str(_dig(load_data_file(key), field))[:10])
                break
            except (TypeError, ValueError):
                continue
        if found is None:
            warn(f"{DATA_FILES[key].name} declares no update date "
                 f"({' / '.join(_DATE_FIELDS[key])}); pages built from it carry no "
                 f"'Updated' stamp")
        _DATE_CACHE[key] = found
    return _DATE_CACHE[key]


def source_date(page):
    """Newest declared update date across a page's data sources (None if none)."""
    dates = [d for d in (data_date(k) for k in page.get("sources", ["content"])) if d]
    return max(dates) if dates else None


def site_updated():
    """Newest declared update date across every data file (drives the © year)."""
    dates = [d for d in (data_date(k) for k in DATA_FILES) if d]
    return max(dates) if dates else None


# ---------------------------------------------------------------------------
# Derived <head> metadata
# ---------------------------------------------------------------------------

_DESC_SUFFIXES = (
    f" — {SITE_NAME}, astrostatistics at the University of Toronto.",
    f" — {SITE_NAME}",
)


def meta_description_clamp(text):
    """Collapse whitespace, strip markup and clamp to 160 characters at a word
    boundary (a hand-written pages.<key>.description goes through this unchanged
    unless it is too long)."""
    body = re.sub(r"\s+", " ", strip_tags(text)).strip()
    if len(body) <= 160:
        return body
    warn(f"meta description is {len(body)} characters; truncated to 160: {body[:60]}…")
    return body[:159].rsplit(" ", 1)[0] + "…"


def meta_description(text):
    """Build a <=160-character meta/OG description from a page tagline: strip markup,
    then append the longest name suffix that still fits."""
    body = re.sub(r"\s+", " ", strip_tags(text)).strip().rstrip(".")
    for suffix in _DESC_SUFFIXES:
        if len(body) + len(suffix) <= 160:
            return body + suffix
    return meta_description_clamp(body)


def _page_description(key, page, data):
    """Per-page description: pages.<key>.description in content.json wins, then a
    registry override, else derived from pages.<key>.tagline (publications gets the
    live pipeline metrics instead, so it can never go stale)."""
    declared = page_meta(data, key).get("description")
    if declared:
        return meta_description_clamp(declared)
    if page.get("description"):
        return page["description"]
    if key == "publications":
        m = _pub_metrics()
        bits = [f'{m.get("totalPapers", 0):,} papers']
        if m.get("totalCitations"):
            bits.append(f'{m["totalCitations"]:,} citations')
        if m.get("hIndex"):
            bits.append(f'h-index {m["hIndex"]}')
        return meta_description("Peer-reviewed publications and preprints — " + ", ".join(bits))
    return meta_description(page_meta(data, key).get("tagline", ""))


def _page_title(key, page, data):
    if page.get("title"):
        return page["title"]
    return f'{esc_text(page_meta(data, key).get("title", key.title()))} · {SITE_NAME}'


# ---------------------------------------------------------------------------
# Document shell (head / nav / footer / scripts) — one copy for every page
# ---------------------------------------------------------------------------

THEME_BOOT = ("<script>(function () { var t = localStorage.getItem('preferred-theme') || 'dark'; "
              "document.documentElement.setAttribute('data-theme', t); })();</script>")

# Every page loads site.js (nav + theme toggle) before its page-specific scripts;
# the theme boot line above is the only inline script left in the shell.
SITE_SCRIPT = "site.js"


def _nav_link(entry, current, root):
    """One nav anchor (in a group menu or top level). aria-current marks this page."""
    if entry.get("page"):
        key = entry["page"]
        label = esc(PAGES[key]["nav"])
        href = f'{root}{PAGES[key]["file"]}'
        cur = ' aria-current="page"' if key == current else ""
        return href, label, cur, ""
    return (url_attr(entry["url"]), esc(entry["label"]), "",
            ' target="_blank" rel="noopener"')


def render_nav(current, root):
    """Primary nav: the brand mark + name, top-level items + dropdown groups, CV,
    theme toggle + hamburger. The class/id contract (.nav-group/.nav-trigger/.menu/
    .nav-open/.open/#hamburger/#theme-toggle/#nav-links) is what site.js wires."""
    out = ['  <nav class="nav" aria-label="Primary">',
           f'    <a class="brand" href="{root}index.html">'
           f'<svg class="mark" aria-hidden="true" focusable="false"><use href="#mark-s"/></svg>'
           f'{SITE_NAME}</a>',
           '    <div class="nav-links" id="nav-links">']
    for entry in NAV:
        if entry.get("items"):
            links = ""
            for item in entry["items"]:
                href, label, cur, ext = _nav_link(item, current, root)
                arrow = ' <span aria-hidden="true">↗</span>' if ext else ""
                links += f'<a href="{href}"{ext}{cur}>{label}{arrow}</a>'
            out.append('      <div class="nav-group">')
            out.append(f'        <button class="nav-trigger" aria-haspopup="true" aria-expanded="false">'
                       f'{entry["label"]} <span aria-hidden="true">▾</span></button>')
            out.append(f'        <div class="menu">{links}</div>')
            out.append('      </div>')
        else:
            href, label, cur, ext = _nav_link(entry, current, root)
            out.append(f'      <a class="nav-item" href="{href}"{cur}>{label}</a>')
    out.append(f'      <a class="nav-item cv-mobile" href="{url_attr(CV_URL)}">Curriculum Vitae</a>')
    out.append('    </div>')
    out.append('    <div class="nav-right">')
    out.append(f'      <a class="cv" href="{url_attr(CV_URL)}">Curriculum Vitae</a>')
    out.append('      <button class="theme-toggle" id="theme-toggle" type="button" aria-label="Toggle dark/light mode">☾</button>')
    out.append('      <button class="theme-toggle hamburger" id="hamburger" type="button" aria-label="Open menu" '
               'aria-expanded="false" aria-controls="nav-links">☰</button>')
    out.append('    </div>')
    out.append('  </nav>')
    return "\n".join(out)


def render_head(key, page, data):
    """<head>: title, derived description, canonical + OG/Twitter, icons, theme boot."""
    root = page.get("root", "")
    title = _page_title(key, page, data)
    desc = esc_text(_page_description(key, page, data))
    out = ['<head>',
           '  <meta charset="UTF-8">',
           '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
           f'  <title>{title}</title>',
           f'  <meta name="description" content="{desc}">']
    if page.get("noindex"):
        out.append('  <meta name="robots" content="noindex">')
    if page.get("canonical"):
        url = f'{SITE_URL}{page["canonical"]}'
        w, h = OG_IMAGE_SIZE
        out += [f'  <link rel="canonical" href="{url}">',
                '  <meta property="og:type" content="website">',
                f'  <meta property="og:site_name" content="{SITE_NAME}">',
                '  <meta property="og:locale" content="en_US">',
                f'  <meta property="og:title" content="{title}">',
                f'  <meta property="og:description" content="{desc}">',
                f'  <meta property="og:url" content="{url}">',
                f'  <meta property="og:image" content="{SITE_URL}/{OG_IMAGE}">',
                f'  <meta property="og:image:width" content="{w}">',
                f'  <meta property="og:image:height" content="{h}">',
                f'  <meta property="og:image:alt" content="{esc_text(OG_IMAGE_ALT)}">',
                '  <meta name="twitter:card" content="summary_large_image">',
                f'  <meta name="twitter:image" content="{SITE_URL}/{OG_IMAGE}">']
    out += ['',
            f'  <link rel="icon" href="{root}favicon.svg" type="image/svg+xml">',
            f'  <link rel="icon" href="{root}favicon-32x32.png" sizes="32x32" type="image/png">',
            f'  <link rel="icon" href="{root}favicon-16x16.png" sizes="16x16" type="image/png">',
            f'  <link rel="apple-touch-icon" href="{root}apple-touch-icon.png">',
            f'  <link rel="manifest" href="{root}site.webmanifest">',
            '  <meta name="theme-color" content="#06080f">',
            '',
            f'  {THEME_BOOT}',
            '']
    schema = render_structured_data(key, page, data)
    if schema:
        out += [schema, '']
    out += [f'  <link rel="alternate" type="application/rss+xml" '
            f'title="{SITE_NAME} · News" href="{root}{FEED_FILE}">',
            '',
            f'  <link rel="stylesheet" href="{root}assets/css/fonts.css">',
            f'  <link rel="stylesheet" href="{root}assets/css/tokens.css">',
            f'  <link rel="stylesheet" href="{root}assets/css/redesign.css">',
            '</head>']
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Structured data (schema.org JSON-LD) — a Person on every indexed page, plus the
# publication list on Publications. Built from the same data as the visible page,
# so it cannot drift from what a reader sees.
# ---------------------------------------------------------------------------

def _json_ld(obj):
    """Serialize one JSON-LD block. `<` is escaped so the payload can never close
    the script element."""
    body = json.dumps(obj, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
    return f'  <script type="application/ld+json">{body}</script>'


def person_schema(data):
    """schema.org Person for the site owner, from content.json."""
    site = data.get("site", {}) or {}
    links = (data.get("sections", {}).get("publications", {}) or {}).get("links", {}) or {}
    contact = (data.get("sections", {}).get("about", {}) or {}).get("contactInfo", {}) or {}
    same_as = [links.get("orcid"), links.get("scholar")]
    github_user = load_data_file("software").get("githubUser")
    if github_user:
        same_as.append(f"https://github.com/{github_user}")
    person = {
        "@type": "Person",
        "name": SITE_NAME,
        "url": f"{SITE_URL}/",
        "image": f"{SITE_URL}/{OG_IMAGE}",
        "sameAs": [u for u in same_as if u],
    }
    home = (data.get("pages", {}) or {}).get("home", {}) or {}
    if home.get("nameZh"):
        # nameZh carries display spacing ("沈 佳 士"); structured data wants the name.
        person["alternateName"] = "".join(home["nameZh"].split())
    if site.get("jobTitle"):
        person["jobTitle"] = site["jobTitle"]
    if contact.get("email"):
        person["email"] = f'mailto:{contact["email"]}'
    aff = site.get("affiliation") or {}
    if aff.get("name"):
        person["affiliation"] = {k: v for k, v in
                                 (("@type", "Organization"), ("name", aff.get("name")),
                                  ("url", aff.get("url"))) if v}
    return person


def render_structured_data(key, page, data):
    """JSON-LD for one page: the Person everywhere, plus a CollectionPage describing
    Publications. 404 (noindex) gets none.

    The 136 papers are deliberately NOT inlined as ScholarlyArticle nodes: measured,
    that adds 60 KB (+11 KB gzipped, +26%) to publications.html, no search engine
    surfaces ScholarlyArticle rich results, and the page already links the complete
    machine-readable record as BibTeX.
    """
    if not page.get("canonical"):
        return ""
    blocks = [{"@context": "https://schema.org", **person_schema(data)}]
    if key == "publications":
        papers = [p for p in load_data_file("publications").get("publications", [])
                  if p.get("year")]
        blocks.append({
            "@context": "https://schema.org",
            "@type": "CollectionPage",
            "url": f'{SITE_URL}{page["canonical"]}',
            "name": _page_title(key, page, data),
            "about": {"@type": "Person", "name": SITE_NAME, "url": f"{SITE_URL}/"},
            "mainEntity": {"@type": "ItemList", "numberOfItems": len(papers)},
            "encoding": {"@type": "MediaObject",
                         "encodingFormat": "application/x-bibtex",
                         "contentUrl": f"{SITE_URL}/{BIBTEX_PATH}"},
        })
    return "\n".join(_json_ld(b) for b in blocks)


def _footer_elsewhere(data):
    """The "Elsewhere" footer column: the author profiles declared in
    sections.publications.links, plus the GitHub account software_data.json fetches."""
    declared = ((data.get("sections", {}).get("publications", {}) or {}).get("links") or {})
    labels = [("ads", "ADS"), ("scholar", "Google Scholar"), ("orcid", "ORCID")]
    links = [(label, declared[key]) for key, label in labels if declared.get(key)]
    user = load_data_file("software").get("githubUser")
    if user:
        links.insert(2, ("GitHub", f"https://github.com/{user}"))
    return "".join(
        f'<li><a href="{url_attr(url)}" target="_blank" rel="noopener">{esc(name)}</a></li>'
        for name, url in links)


def render_footer(page, data, root):
    """Site footer: the brand lockup, one link column per NAV group plus "Elsewhere",
    and the copyright line. Both dates come from the data files (see data_date): the
    stamp from this page's own sources, the © year from the newest of all of them."""
    note = page.get("footer", DEFAULT_FOOTER_NOTE)
    stamp = source_date(page)
    updated = f' · Updated {stamp.strftime("%B %Y")}' if stamp else ""
    year = site_updated()
    copyright_ = f"© {year.year} " if year else ""
    site = data.get("site", {}) or {}

    columns = []
    for entry in NAV:                       # the nav registry IS the footer sitemap
        if not entry.get("items"):
            continue
        rows = ""
        for item in entry["items"]:
            href, label, _cur, ext = _nav_link(item, None, root)
            rows += f'<li><a href="{href}"{ext}>{label}</a></li>'
        columns.append((entry["label"], rows))
    columns.append(("Elsewhere", _footer_elsewhere(data)))
    cols_html = "".join(
        f'        <div><h2>{label}</h2><ul>{rows}</ul></div>\n'
        for label, rows in columns if rows)

    blurb = esc(site.get("jobTitle", ""))
    if site.get("affiliation", {}).get("name"):
        blurb = f'{blurb} · {esc(site["affiliation"]["name"])}' if blurb else esc(site["affiliation"]["name"])
    return ('  <footer class="site-footer">\n'
            '    <div class="container">\n'
            '      <div class="foot">\n'
            '        <div>\n'
            f'          <a class="brand" href="{root}index.html">'
            f'<svg class="mark" aria-hidden="true" focusable="false"><use href="#mark-s"/></svg>'
            f'{SITE_NAME}</a>\n'
            f'          <p class="foot-blurb">{blurb}</p>\n'
            '        </div>\n'
            f'{cols_html}'
            '      </div>\n'
            '      <div class="foot-copy">\n'
            f'        <span>{copyright_}{SITE_NAME} · <span class="zh">沈佳士</span></span>\n'
            f'        <span>{note}{updated}</span>\n'
            '      </div>\n'
            '    </div>\n'
            '  </footer>')


# The three stages the hero canvas draws, labelled along its bottom edge.
_HERO_LABELS = [("hl-obs", "Observations"), ("hl-net", "Network"), ("hl-post", "Posterior")]


def render_hero(data):
    """Home hero: the animated network canvas + kicker/name/tagline/CTAs from
    pages.home. One solid action (.btn); every further CTA is a text link (.link)."""
    home = page_meta(data, "index")
    ctas = ""
    for i, cta in enumerate(home.get("cta", [])):
        cls = "btn" if i == 0 and cta.get("type") == "primary" else "link"
        ctas += f'<a class="{cls}" href="{url_attr(cta.get("url", "#"))}">{esc(cta.get("text", ""))}</a>'
    labels = "".join(f'<span class="{cls}">{esc(text)}</span>' for cls, text in _HERO_LABELS)
    return ('    <section class="hero">\n'
            '      <canvas id="hero-sky" aria-hidden="true"></canvas>\n'
            '      <div class="scrim" aria-hidden="true"></div>\n'
            '      <div class="container">\n'
            '        <div class="hero-inner">\n'
            f'          <p class="kicker">{esc_text(home.get("kicker", ""))}</p>\n'
            f'          <h1>{esc_text(home.get("title", SITE_NAME))}'
            f'<span class="zh">{esc_text(home.get("nameZh", ""))}</span></h1>\n'
            f'          <p class="tagline">{home.get("tagline", "")}</p>\n'
            f'          <div class="cta">{ctas}</div>\n'
            '        </div>\n'
            '      </div>\n'
            f'      <div class="hero-labels" aria-hidden="true">{labels}</div>\n'
            '    </section>')


def generate_page_header(page):
    """Render a secondary page's header band (kicker / title / tagline) from pages.<page>.
    kicker + title are plain text (escaped); tagline is emitted as-is so it may carry
    inline markup (e.g. <strong>)."""
    return (
        f'<p class="kicker">{esc_text(page.get("kicker", ""))}</p>\n'
        f'        <h1 class="pub-h1">{esc_text(page.get("title", ""))}</h1>\n'
        f'        <p class="pub-sub">{page.get("tagline", "")}</p>'
    )


def render_notfound(data):
    """The 404 body, from pages.notfound in content.json (kicker/title/body/cta) —
    the same data path as every other page's header band."""
    meta = page_meta(data, "404")
    cta = (meta.get("cta") or {})
    return ('  <main id="main-content" class="notfound-main" tabindex="-1">\n'
            '    <div class="container" id="notfound-content">\n'
            '<div class="notfound-card" data-chip>\n'
            f'      <p class="kicker">{esc_text(meta.get("kicker", ""))}</p>\n'
            f'      <h1 class="notfound-title">{esc_text(meta.get("title", ""))}</h1>\n'
            f'      <p class="notfound-body">{esc_text(meta.get("body", ""))}</p>\n'
            f'      <a class="btn" href="{url_attr(cta.get("url", "/index.html"))}">'
            f'{esc_text(cta.get("text", "Return home"))}</a>\n'
            '      </div>\n'
            '</div>\n'
            '  </main>')


def render_main(key, page, data, content):
    """<main>: the Home hero + section grid, the secondary header band + content
    container, or the hand-written 404 body."""
    if page["layout"] == "notfound":
        return render_notfound(data)
    out = ['  <main id="main-content" tabindex="-1">']
    if page["layout"] == "hero":
        out.append(render_hero(data))
        for sec_id, cls, html in content:
            out.append(f'\n    <section class="{cls}" id="{sec_id}">\n{html}\n</section>')
    else:
        meta = page_meta(data, key)
        out.append('    <section class="pub-header">')
        out.append(f'      <div class="container" id="{key}-header">')
        out.append(generate_page_header(meta))
        out.append('</div>')
        out.append('    </section>')
        out.append('')
        out.append('    <section class="section section--flush">')
        out.append(f'      <div id="{container_id(key)}">')
        out.append(content)
        out.append('</div>')
        out.append('    </section>')
    out.append('  </main>')
    return "\n".join(out)


def _credit_comment(data):
    """site.credit from content.json, as a build credit in the document source (it is
    an attribution for how the site was made, not page copy)."""
    credit = (data.get("site", {}) or {}).get("credit", "")
    return f"<!-- {esc_text(credit).replace('--', '- -')} -->\n" if credit else ""


def render_shell(key, data, content):
    """Render one complete document from the registry + generated content."""
    page = PAGES[key]
    root = page.get("root", "")
    scripts = "".join(f'\n  <script src="{root}assets/js/redesign/{s}" defer></script>'
                      for s in [SITE_SCRIPT] + list(page.get("scripts", [])))
    return (
        '<!DOCTYPE html>\n'
        '<html lang="en" data-theme="dark">\n'
        '<!-- Generated by scripts/build_html.py from assets/data/*.json — edit the data, not this file. -->\n'
        f'{_credit_comment(data)}'
        f'{render_head(key, page, data)}\n'
        '\n'
        '<body>\n'
        f'{SPRITE}\n'
        '  <svg id="board" aria-hidden="true"></svg>\n'
        '\n'
        '  <a class="skip-link" href="#main-content">Skip to main content</a>\n'
        '\n'
        f'{render_nav(key, root)}\n'
        '\n'
        f'{render_main(key, page, data, content)}\n'
        '\n'
        f'{render_footer(page, data, root)}\n'
        f'{scripts}\n'
        '</body>\n'
        '</html>\n'
    )


def write_sitemap():
    """Write sitemap.xml from the registry: one <url> per indexed page, with a
    lastmod derived from that page's data sources."""
    rows = []
    for key, page in PAGES.items():
        if not page.get("sitemap") or not page.get("canonical"):
            continue
        stamp = source_date(page)
        lastmod = f'        <lastmod>{stamp.isoformat()}</lastmod>\n' if stamp else ""
        rows.append('    <url>\n'
                    f'        <loc>{SITE_URL}{page["canonical"]}</loc>\n'
                    f'{lastmod}'
                    f'        <priority>{page["sitemap"]}</priority>\n'
                    '    </url>')
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
           + "\n".join(rows) + "\n</urlset>\n")
    old = SITEMAP_XML.read_text(encoding="utf-8") if SITEMAP_XML.exists() else None
    if old != xml:
        SITEMAP_XML.write_text(xml, encoding="utf-8")
        print("  -> Updated sitemap.xml")
    return xml

_RFC822_MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def _news_date(item):
    """(date, RFC-822 string) for a news item. Items carry month precision
    ("Aug 2026"), so they are dated to the 1st of that month."""
    year = int(item.get("year") or 0) or 1970
    month = term_month(item.get("date", "")) or 1
    return date(year, month, 1), _rfc822(date(year, month, 1))


def _rfc822(d):
    """RFC-822 date for RSS (no locale dependency, no time of day)."""
    return f"{d.day:02d} {_RFC822_MONTHS[d.month - 1]} {d.year} 00:00:00 +0000"


def write_feed(data):
    """Write feed.xml: an RSS 2.0 feed of sections.news.items.

    Item guids are stable, non-permalink tags built from the date + title slug, so a
    reader never re-shows an item because an unrelated item was added above it.
    """
    news = (data.get("sections", {}).get("news", {}) or {})
    items = news.get("items", []) or []
    types = news.get("types", {}) or {}
    news_url = f'{SITE_URL}{PAGES["news"]["canonical"]}'
    rows, seen = [], set()
    for item in sorted(items, key=lambda n: _news_date(n)[0], reverse=True):
        stamp, rfc822 = _news_date(item)
        title = strip_tags(item.get("title", ""))
        guid = f'tag:joshspeagle.com,{stamp.isoformat()}:news/{slug(title)[:60]}'
        while guid in seen:                       # two items, one month, one slug
            guid += "-b"
        seen.add(guid)
        label = (types.get(item.get("type")) or {}).get("label", "")
        body = strip_tags(item.get("blurb", ""))
        rows.append('    <item>\n'
                    f'      <title>{esc_text(title)}</title>\n'
                    f'      <link>{esc_text(item.get("link") or news_url)}</link>\n'
                    f'      <guid isPermaLink="false">{esc_text(guid)}</guid>\n'
                    f'      <pubDate>{rfc822}</pubDate>\n'
                    + (f'      <category>{esc_text(label)}</category>\n' if label else "")
                    + f'      <description>{esc_text(body)}</description>\n'
                    '    </item>')
    built = data_date("content")
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n'
           '  <channel>\n'
           f'    <title>{SITE_NAME} · News</title>\n'
           f'    <link>{news_url}</link>\n'
           f'    <description>News and press from {SITE_NAME}, astrostatistics at the '
           'University of Toronto.</description>\n'
           '    <language>en-us</language>\n'
           f'    <atom:link href="{SITE_URL}/{FEED_FILE}" rel="self" type="application/rss+xml"/>\n'
           + (f'    <lastBuildDate>{_rfc822(built)}</lastBuildDate>\n' if built else "")
           + "\n".join(rows) + '\n  </channel>\n</rss>\n')
    old = FEED_XML.read_text(encoding="utf-8") if FEED_XML.exists() else None
    if old != xml:
        FEED_XML.write_text(xml, encoding="utf-8")
        print(f"  -> Updated {FEED_FILE}")
    return xml


# The four research areas, in content.json order: (sprite icon id, area key).
_HOME_ICONS = [("ic-sla", "sla"), ("ic-ii", "ii"), ("ic-ic", "ic"), ("ic-du", "du")]

# The ART panel's two highlights, in content.json order (the emoji in the data are
# ignored — Design G draws them from the sprite).
_ART_ICONS = ["ic-sla", "ic-team"]


def _use(icon_id, cls):
    """One sprite glyph (see pages_shared.SPRITE)."""
    return f'<svg class="{cls}" aria-hidden="true" focusable="false"><use href="#{icon_id}"/></svg>'



def _webp(src):
    """Return the .webp sibling path for a raster image src."""
    return re.sub(r"\.(jpe?g|png)$", ".webp", src, flags=re.I)


def _dog_photos(bio):
    """Render the personal dog photos (used in the About section)."""
    photos = ""
    for ph in bio.get("dogPhotos", []):
        if not ph.get("src"):
            continue
        if ph.get("creditLink"):
            credit = f' <a href="{url_attr(ph["creditLink"])}" target="_blank" rel="noopener">{esc(ph.get("creditName", ""))}</a>'
        elif ph.get("creditName"):
            credit = f' {esc(ph["creditName"])}'
        else:
            credit = ""
        photos += (
            '<figure class="dog-photo"><picture>'
            f'<source srcset="{url_attr(_webp(ph["src"]))}" type="image/webp">'
            f'<img src="{url_attr(ph["src"])}" alt="{esc(ph.get("alt", ""))}" loading="lazy" width="800" height="533">'
            '</picture>'
            f'<figcaption>{esc(ph.get("caption", ""))}{credit}</figcaption></figure>'
        )
    return f'<div class="dog-photos">{photos}</div>' if photos else ""


def home_section(data, key):
    """Headings for one Home section, from pages.home.sections.<key> in content.json."""
    return ((data.get("pages", {}).get("home", {}).get("sections", {}) or {}).get(key) or {})


def sec_head(title):
    """A Home section head: a serif h2 followed by a copper rule that starts on a
    hollow via and ends on a square pad (§5). Replaces the old mono eyebrows — only
    the hero keeps a kicker."""
    return (f'<div class="sec-head"><h2 class="section-title">{esc(title)}</h2>'
            '<div class="rule" aria-hidden="true"></div></div>')


def generate_home_about(data):
    about = data["sections"]["about"]
    bio = data["sections"].get("biography", {})
    pi = about.get("profileImage", {})
    hb = about.get("highlightBox", {})
    ci = about.get("contactInfo", {})

    photo = ""
    if pi.get("src"):
        photo = (
            '<figure class="profile-figure" data-chip>'
            '<picture>'
            f'<source srcset="{url_attr(_webp(pi["src"]))}" type="image/webp">'
            f'<img class="profile-image" src="{url_attr(pi["src"])}" alt="{esc(pi.get("alt", ""))}" '
            'width="384" height="513" loading="lazy">'
            '</picture></figure>'
        )
    highlight = ""
    if hb.get("content"):
        highlight = (
            '<aside class="callout" data-chip>'
            f'<h3>{esc(hb.get("title", ""))}</h3>'
            f'<p>{hb.get("content", "")}</p></aside>'
        )
    contact = ""
    if ci.get("email"):
        contact = (
            '<dl class="contact-info">'
            f'<dt>Email</dt><dd><a href="mailto:{url_attr(ci["email"])}">{esc(ci["email"])}</a></dd>'
            f'<dt>Office</dt><dd>{esc(ci.get("office", ""))}</dd></dl>'
        )
    note = bio.get("personalNote", "")
    personal = f'<p class="about-personal">{esc(note)}</p>' if note else ""
    dogs = _dog_photos(bio)
    return (
        '<div class="container">\n'
        + sec_head(about.get("title", "About")) + '\n'
        '<div class="intro-grid">\n'
        '<div class="intro-body">'
        f'<p class="about">{about.get("content", "")}</p>'
        f'{highlight}{contact}'
        '</div>\n'
        f'{photo}\n'
        '</div>\n'
        f'{personal}\n'
        f'{dogs}\n'
        "</div>"
    )


def _pub_metrics():
    """Pipeline-computed publication metrics (totalPapers/totalCitations/hIndex/i10Index)."""
    return load_data_file("publications").get("metrics", {}) or {}


def _area_paper_counts():
    """How many papers are FILED under each of the four areas (argmax of
    categoryProbabilities — the same rule the Publications chips use, so the Home
    counts and the Publications chips can never disagree)."""
    counts = {"sla": 0, "ii": 0, "ic": 0, "du": 0}
    for pub in load_data_file("publications").get("publications", []):
        if pub.get("year"):
            counts[_pub_cat_key(pub)] += 1
    return counts


def _mentee_count(data):
    """Everyone ever mentored: the current menteesByStage cohorts plus the completed
    ones (the same all-time total the Mentorship page reports)."""
    mbs = ((data.get("sections", {}).get("mentorship", {}) or {}).get("menteesByStage") or {})
    completed = mbs.get("completed") or {}
    return sum(len(v) for k, v in mbs.items() if k != "completed" and isinstance(v, list)) \
        + sum(len(v) for v in completed.values() if isinstance(v, list))


def generate_home_research(data):
    research = data["sections"]["research"]
    areas = research["areas"][:4]
    counts = _area_paper_counts()
    cards = []
    for i, area in enumerate(areas):
        icon, cls = _HOME_ICONS[i] if i < len(_HOME_ICONS) else _HOME_ICONS[-1]
        n = counts.get(cls, 0)
        tally = f'<div class="meta-via">{n} paper{"s" if n != 1 else ""}</div>' if n else ""
        cards.append(
            f'<article class="research-card {cls}" data-chip data-cat="{cls}">'
            f'{_use(icon, "icon")}'
            f'<h3>{esc(area.get("title", ""))}</h3>'
            f'<p>{esc(area.get("description", ""))}</p>{tally}</article>'
        )
    head = home_section(data, "research")
    intro = esc(head.get("intro", ""))
    additional = research.get("additionalContent", "")
    pubs = research.get("publications", {})
    publinks = "".join(
        f'<a href="{url_attr(l.get("url", "#"))}" target="_blank" rel="noopener">{esc(l.get("name", ""))}</a>'
        for l in pubs.get("links", [])
    )
    # Auto-computed metric pads (pipeline-maintained publication metrics + the
    # all-time mentee count).
    m = _pub_metrics()
    metric_defs = [(m.get("totalPapers"), "Papers"),
                   (m.get("totalCitations"), "Citations"),
                   (m.get("hIndex"), "h-index"),
                   (_mentee_count(data), "Mentees")]
    metrics_html = "".join(
        f'<div class="pub-metric"><span class="n">{v:,}</span><span class="l">{esc(l)}</span></div>'
        for v, l in metric_defs if v
    )
    pubbox = ""
    if metrics_html or publinks:
        pubbox = (
            '<article class="pub-metrics-chip" data-chip>'
            f'<div class="pub-metrics">{metrics_html}</div>'
            f'<div class="pub-links"><span>{esc(pubs.get("intro", ""))}</span>{publinks}'
            '<a class="go" href="publications.html">Browse all publications, metrics &amp; figures →</a>'
            '</div></article>'
        )
    context = f'<p class="research-context">{esc(additional)}</p>' if additional else ""
    return (
        '<div class="container">\n'
        + sec_head(head.get("title", "")) + '\n'
        f'<p class="section-intro">{intro}</p>\n'
        f'<div class="research-grid" data-bus>{"".join(cards)}</div>\n'
        f'{context}\n'
        f'{pubbox}\n'
        "</div>"
    )


def _inline_logo(logo):
    """Inline the ART logo SVG with fill->currentColor so it can be themed via CSS."""
    src = (logo or {}).get("src", "")
    if not src.endswith(".svg"):
        return ""
    try:
        svg = (PROJECT_ROOT / src).read_text(encoding="utf-8")
    except OSError:
        return ""
    svg = re.sub(r"<\?xml[^>]*\?>\s*", "", svg)
    svg = svg.replace('fill="#2f559d"', 'fill="currentColor"')
    svg = svg.replace("<svg ", '<svg class="art-logo-svg" aria-hidden="true" ', 1)
    return svg


def generate_home_team(data):
    team = data["sections"]["team"]
    logo = _inline_logo(team.get("logo"))
    logo_html = (f'<figure class="art-logo" aria-label="{esc(team.get("logo", {}).get("alt", ""))}">'
                 f'{logo}</figure>') if logo else ""
    hls = ""
    for i, h in enumerate(team.get("highlights", [])):
        icon = _ART_ICONS[i] if i < len(_ART_ICONS) else _ART_ICONS[-1]
        hls += ('<div class="art-highlight">'
                f'{_use(icon, "art-hl-icon")}'
                f'<div><h3>{esc(h.get("title", ""))}</h3>'
                f'<p>{esc(h.get("content", ""))}</p></div></div>')
    head = home_section(data, "team")
    # The eyebrow link reuses the group's own CTA url — one source of truth for it.
    group_url = next((c.get("url") for c in team.get("cta", []) if c.get("url", "").startswith("http")), "")
    eyebrow_link = (
        f'<a class="art-ext" href="{url_attr(group_url)}" target="_blank" rel="noopener">'
        f'{esc(urlparse(group_url).netloc)} <span aria-hidden="true">↗</span></a>'
    ) if group_url else ""
    # Design G retires the ✦ glyph; the eyebrow is a square pad like every other label.
    eyebrow_text = esc(head.get("eyebrow", "").replace("✦", "").strip())
    btns = []
    for i, c in enumerate(team.get("cta", [])):
        url = c.get("url", "#")
        ext = url.startswith("http")
        attrs = ' target="_blank" rel="noopener"' if ext else ""
        arrow = ' <span aria-hidden="true">↗</span>' if ext else ""
        cls = "btn" if i == 0 else "link"
        btns.append(f'<a class="{cls}" href="{url_attr(url)}"{attrs}>{esc(c.get("text", ""))}{arrow}</a>')
    return (
        '<div class="container">\n'
        '<article class="art-panel" data-chip>\n'
        f'{logo_html}\n'
        '<div class="art-body">\n'
        f'<p class="art-eyebrow"><span class="badge">{eyebrow_text}</span>{eyebrow_link}</p>\n'
        f'<h2>{esc(team.get("title", ""))}</h2>\n'
        f'<p class="team-tagline">{esc(team.get("tagline", ""))}</p>\n'
        f'<p class="lead">{team.get("content", "")}</p>\n'
        f'<div class="art-highlights">{hls}</div>\n'
        f'<div class="cta">{"".join(btns)}</div>\n'
        '</div>\n'
        '</article>\n'
        "</div>"
    )


def _opp_link(l):
    name = esc(l.get("name", ""))
    out = f'<a href="{url_attr(l["url"])}" target="_blank" rel="noopener">{name}</a>' if l.get("url") else name
    if l.get("abbr"):
        out += f' ({esc(l["abbr"])})'
    elif l.get("note"):
        out += f' <span class="opp-note">({esc(l["note"])})</span>'
    return out


def _opp_links_html(card):
    """Render whatever link groups a card has: fellowships, programs, or opportunities."""
    out = ""
    for key, default in (("fellowships", "Fellowships:"), ("programs", "Programs:")):
        grp = card.get(key)
        if grp and grp.get("links"):
            links = ", ".join(_opp_link(l) for l in grp["links"])
            out += f'<p class="opp-links"><strong>{esc(grp.get("intro", default))}</strong> {links}</p>'
    opps = card.get("opportunities")
    if isinstance(opps, list) and opps:
        links = ", ".join(_opp_link(o) for o in opps)
        out += f'<p class="opp-links"><strong>Programs:</strong> {links}</p>'
    return out


def generate_home_collab(data):
    collab = data["sections"]["collaboration"]
    vals = collab.get("values", {})
    val_items = "".join(
        f'<article class="card" data-chip><h3>{esc(v.get("title", ""))}</h3>'
        f'<p>{esc(v.get("content", ""))}</p></article>'
        for v in vals.get("items", [])
    )
    values_html = f'<div class="values-grid" data-bus>{val_items}</div>' if val_items else ""
    opp = collab.get("opportunities", {})
    # The opportunity cards are chips visually but carry no trace: the density rule
    # keeps Home to the eight blocks the trunk actually feeds.
    cards = "".join(
        f'<article class="card opp-card"><h3>{esc(c.get("title", ""))}</h3>'
        f'<p>{esc(c.get("content", ""))}</p>{_opp_links_html(c)}</article>'
        for c in opp.get("cards", [])
    )
    opp_heading = f'<h3 class="opp-heading">{esc(opp.get("title", "Opportunities"))}</h3>' if cards else ""
    return (
        '<div class="container">\n'
        + sec_head(collab.get("title", "")) + '\n'
        f'<p class="section-intro">{esc(collab.get("intro", ""))}</p>\n'
        f'{values_html}\n'
        f'{opp_heading}\n'
        f'<div class="grid-3 opp-grid">{cards}</div>\n'
        "</div>"
    )


def generate_biography(data):
    """Career timeline for the dedicated Biography page (#biography-content).

    The page shell supplies the title/tagline header band, so this emits only the
    timeline. (Personal note + dog photos live in the Home 'About' section.)

    The timeline is drawn as a board trace: entries run chronologically top->bottom,
    each event is a hollow via on a copper trunk, the current role is an energy #star4
    (plus the NOW pad), and an entry flagged `"concurrent": true` in content.json hangs
    off the trunk as an indented branch (45 deg out, parallel, 45 deg back in) instead
    of pretending to be the next step in the sequence. The trunk segment is drawn per
    item (.tl-item::after) rather than once for the whole column, so the LAST entry can
    fade its own tail out below the current role without any magic offsets.
    """
    bio = data["sections"]["biography"]
    timeline = bio.get("timeline", []) or []
    star = '<svg class="tl-star" aria-hidden="true" focusable="false"><use href="#star4"/></svg>'
    parts = []
    for i, t in enumerate(timeline):
        cls = "tl-item"
        if t.get("current"):
            cls += " current"
        if t.get("concurrent"):
            cls += " concurrent"
        if i == len(timeline) - 1:
            cls += " tl-tail"           # the trunk fades out under the last entry
        flags = ""
        if t.get("current"):
            flags += '<span class="tl-now">Now</span>'
        if t.get("concurrent"):
            flags += '<span class="tl-conc">Concurrent</span>'
        branch = '<span class="tl-branch" aria-hidden="true"></span>' if t.get("concurrent") else ""
        parts.append(
            f'<div class="{cls}">{branch}'
            + (star if t.get("current") else "")
            + f'<div class="tl-date">{esc(t.get("date", ""))}</div>'
            f'<div class="tl-title">{esc(t.get("title", ""))}{flags}</div>'
            f'<div class="tl-loc">{esc(t.get("location", ""))}</div>'
            f'<div class="tl-content">{t.get("content", "")}</div>'
            "</div>"
        )
    items = "".join(parts)
    return (f'<div class="container">\n<div class="timeline" data-chip>{items}</div>\n</div>')


# ---------------------------------------------------------------------------
# Publications page generator (redesign)
# ---------------------------------------------------------------------------

# researchArea label -> (key, badge label with escaped &)
_PUB_CAT_MAP = {
    "Statistical Learning & AI": ("sla", "Statistical Learning &amp; AI"),
    "Interpretability & Insight": ("ii", "Interpretability &amp; Insight"),
    "Inference & Computation": ("ic", "Inference &amp; Computation"),
    "Discovery & Understanding": ("du", "Discovery &amp; Understanding"),
}

# Stable order for emitting category badges (matches the 4 areas)
_PUB_CAT_ORDER = [
    "Statistical Learning & AI",
    "Interpretability & Insight",
    "Inference & Computation",
    "Discovery & Understanding",
]


# Category key -> badge label (reverse of _PUB_CAT_MAP, in _PUB_CAT_ORDER order)
_PUB_CAT_LABEL = {key: label for key, label in _PUB_CAT_MAP.values()}


def _cat_probs(pub):
    """(category name, probability) for the four areas, in badge order."""
    probs = pub.get("categoryProbabilities", {}) or {}
    out = []
    for cat in _PUB_CAT_ORDER:
        try:
            out.append((cat, float(probs.get(cat, 0))))
        except (TypeError, ValueError):
            out.append((cat, 0.0))
    return out


def _pub_badge_keys(pub):
    """Category keys BADGED on a card: every area with probability >= 0.20, so a
    paper can advertise that it spans more than one area."""
    keys = [_PUB_CAT_MAP[cat][0] for cat, prob in _cat_probs(pub) if prob >= 0.20]
    return keys or [_pub_cat_key(pub)]


def _pub_cat_key(pub):
    """The single area a paper is FILED under: argmax(categoryProbabilities), which
    the pipeline also stores as researchArea. Card accent, data-cat filter key and
    chip count all read this one value, so the stripe you see is the chip you clicked
    and the chips partition the corpus (D5)."""
    cat, prob = max(_cat_probs(pub), key=lambda cp: cp[1])
    if prob > 0:
        return _PUB_CAT_MAP[cat][0]
    return _PUB_CAT_MAP.get(pub.get("researchArea", ""), ("du", ""))[0]


# Group bylines that must render verbatim rather than as "F. Last" (D15).
_COLLAB_RE = re.compile(r"\b(collaboration|consortium|team|survey)\b", re.I)


def _format_author(author):
    """Format one author for display: 'Last, First M.' and 'First M. Last' both become
    'F. Last'; collaboration/consortium bylines and all-caps acronyms render verbatim.
    Speagle is wrapped in <strong>. Returns the escaped HTML string."""
    is_speagle = "speagle" in author.lower()
    name = author.strip()
    if _COLLAB_RE.search(name) or ("," not in name and name.isupper() and len(name) > 1):
        # Collaboration/consortium bylines and acronyms are not personal names.
        return f"<strong>{esc(name)}</strong>" if is_speagle else esc(name)
    if "," in author:
        last, _, first = author.partition(",")
        last = last.strip()
        first = first.strip()
    else:
        parts = author.strip().split()
        if len(parts) >= 2:
            last = parts[-1]
            first = " ".join(parts[:-1])
        else:
            last = author.strip()
            first = ""
    initial = ""
    fp = first.strip()
    if fp:
        # Use the first alphabetic character of the first name as the initial
        for ch in fp:
            if ch.isalpha():
                initial = ch.upper() + ". "
                break
    display = esc(f"{initial}{last}".strip())
    if is_speagle:
        display = f"<strong>{display}</strong>"
    return display


def _format_authors_html(authors):
    """Show first 3 authors as 'F. Last', append ' et al.' if more than 3."""
    if not authors:
        return ""
    shown = [_format_author(a) for a in authors[:3]]
    html = ", ".join(shown)
    if len(authors) > 3:
        html += " et al."
    return html


def _truncate(s, n=320):
    """Clean + escape + truncate prose at a word boundary for the featured abstract."""
    s = clean_text(s)
    if len(s) <= n:
        return esc(s)
    return esc(s[:n].rsplit(" ", 1)[0]) + "…"


def _generate_paper_card(pub, board=False):
    """Build a .paper card. board=True adds the abstract for the Featured spotlight."""
    title = clean_text(pub.get("title", ""))
    year = pub.get("year", "")
    journal = _venue(pub)
    authors = pub.get("authors", []) or []
    cites_int = int(pub.get("citations", 0) or 0)
    cites_comma = f"{cites_int:,}"

    catkey = _pub_cat_key(pub)

    role = pub.get("authorshipCategory")
    is_student = role == "student"
    is_postdoc = role == "postdoc"
    is_featured = bool(pub.get("featured"))

    # Class list and authorship accent
    cls = f"paper {catkey}"
    if board:
        cls += " feat-card"
    if is_student:
        cls += " student"
    elif is_postdoc:
        cls += " postdoc"

    # The role rides the card's metadata line (and the chip's top edge), so it is not
    # also a tag in the same hue as the category badges beside it (audit A5).
    role_label = "Student-led" if is_student else ("Postdoc-led" if is_postdoc else "")
    tags = '<span class="tag feat">★ Featured</span>' if is_featured else ""

    # Badges for every area >= 0.20; the filter key/accent is the argmax area only.
    badges = "".join(f'<span class="badge b-{k}">{_PUB_CAT_LABEL[k]}</span>'
                     for k in _pub_badge_keys(pub))

    # Resource links: ADS · arXiv · DOI (whichever exist)
    ads = pub.get("adsUrl")
    arxiv = pub.get("arxivId")
    doi = pub.get("doi")
    arxiv_url = f"https://arxiv.org/abs/{arxiv}" if arxiv else ""
    doi_url = f"https://doi.org/{doi}" if doi else ""
    links = ""
    if ads:
        links += f'<a class="reslink" href="{url_attr(ads)}" target="_blank" rel="noopener">ADS</a>'
    if arxiv_url:
        links += f'<a class="reslink" href="{url_attr(arxiv_url)}" target="_blank" rel="noopener">arXiv</a>'
    if doi_url:
        links += f'<a class="reslink" href="{url_attr(doi_url)}" target="_blank" rel="noopener">DOI</a>'

    # Title links to the best available target (arXiv -> ADS -> DOI)
    title_href = arxiv_url or ads or doi_url
    title_inner = esc(title)
    title_html = (
        f'<a href="{url_attr(title_href)}" target="_blank" rel="noopener">{title_inner}</a>'
        if title_href else title_inner
    )

    authors_html = _format_authors_html(authors)
    cite_str = f"{cites_comma} citation{'s' if cites_int != 1 else ''}" if cites_int else ""
    # byline = who wrote it and how often it has been cited; the year, the venue and my
    # role are the card's metadata line above the title.
    meta = " · ".join(part for part in [authors_html, cite_str] if part)

    abstract_html = ""
    if board and pub.get("abstract"):
        abstract_html = f'<p class="paper-abstract">{_truncate(pub["abstract"], 340)}</p>'

    # Featured (board) cards are pinned decoration, not list items — leaving off
    # data-lv-item keeps listview.js from counting or filtering them twice.
    lv = "" if board else " data-lv-item"
    return (
        f'<article class="{cls}"{lv} data-cat="{catkey}" data-year="{year}" '
        f'data-num="{cites_int}" data-title="{attr_esc(title)}" '
        f'data-search="{attr_esc(title + " " + " ".join(authors))}">'
        f'{card_meta(str(year), _venue_short(pub), (role_label, True))}'
        f'<h3 class="paper-title">{title_html}</h3>'
        f'<div class="paper-meta">{meta}</div>'
        f'<div class="paper-badges">{tags}{badges}'
        f'<span class="paper-links">{links}</span></div>'
        f'{abstract_html}'
        f'</article>'
    )


# Bibcode journal code -> venue label, so a paper with no `journal` still shows a
# venue when its bibcode says which one (D14). Codes are bibcode[4:9].
_BIBCODE_JOURNALS = {
    "ApJ": "The Astrophysical Journal",
    "ApJS": "The Astrophysical Journal Supplement Series",
    "ApJL": "The Astrophysical Journal Letters",
    "AJ": "The Astronomical Journal",
    "MNRAS": "Monthly Notices of the Royal Astronomical Society",
    "A&A": "Astronomy and Astrophysics",
    "JCAP": "Journal of Cosmology and Astroparticle Physics",
    "Natur": "Nature",
    "NatAs": "Nature Astronomy",
    "PASP": "Publications of the Astronomical Society of the Pacific",
    "arXiv": "arXiv e-prints",
}


# Bibcode journal code -> the short venue the card's metadata line prints. Codes not
# listed here (or papers with no bibcode) fall back to _venue()'s full journal name.
_VENUE_SHORT = {
    "ApJ": "ApJ", "ApJS": "ApJS", "ApJL": "ApJL", "AJ": "AJ", "MNRAS": "MNRAS",
    "A&A": "A&A", "PASJ": "PASJ", "PASP": "PASP", "JCAP": "JCAP", "OJAp": "OJAp",
    "BAAS": "BAAS", "arXiv": "arXiv", "Natur": "Nature", "NatAs": "Nature Astron.",
    "PhRvD": "Phys. Rev. D", "PhDT": "PhD thesis",
}


def _venue_short(pub):
    """Compact venue for a card's metadata line: the bibcode's journal code when it is
    a familiar abbreviation, else the full journal name _venue() already derives."""
    bibcode = str(pub.get("bibcode") or "")
    if len(bibcode) >= 9:
        short = _VENUE_SHORT.get(bibcode[4:9].strip("."))
        if short:
            return short
    return _venue(pub)


def _venue(pub):
    """Display venue: the stored journal, else derived from the bibcode journal code."""
    journal = (pub.get("journal") or "").strip()
    if journal:
        return journal
    bibcode = str(pub.get("bibcode") or "")
    if len(bibcode) >= 9:
        return _BIBCODE_JOURNALS.get(bibcode[4:9].strip("."), "")
    return ""


# ---------------------------------------------------------------------------
# Publication figures
#
# Every figure is HTML first: the axis ticks, the legend keys and the direct
# labels are real HTML text laid out in a CSS grid AROUND the plot box, so they
# never scale with the drawing. (When the whole chart was one viewBox-scaled SVG,
# the 11px axis type rendered at 6.6px on a 1440 desktop and 3.9px on a phone —
# audit A4.) Only geometry lives inside .pf-plot: bars, dots, gridlines and hit
# targets as positioned HTML, and line/area paths in a stretched
# <svg preserveAspectRatio="none"> whose strokes are non-scaling.
#
# The per-year hit targets are tab stops carrying an aria-label (and a data-tip
# for the visual tooltip in pubchart.js). They deliberately do NOT carry
# role="img": that role marks an atomic, non-interactive graphic, which
# contradicts a tab stop (D21). The chart root stays role="group" + aria-label,
# the correct container role for a graphic that holds focusable children.
# ---------------------------------------------------------------------------

def _n(v):
    """Compact number for an inline style/coordinate (no trailing zeros)."""
    return f"{v:.2f}".rstrip("0").rstrip(".") or "0"


def _tip(text):
    """A focusable, hoverable hit target's shared attributes."""
    t = esc(text).replace('"', "&quot;")
    return f'tabindex="0" aria-label="{t}" data-tip="{t}"'


def _pf_grid(ticks, yp):
    """Copper dotted silkscreen gridlines at the given values."""
    return "".join(f'<span class="pf-gl" style="top:{_n(yp(t))}%"></span>'
                   for t in ticks if t > 0)


def _pf_yticks(ticks, yp, fmt="{:,}"):
    return "".join(f'<span class="pf-yt" style="top:{_n(yp(t))}%">{fmt.format(t)}</span>'
                   for t in ticks if t > 0)


def _pf_xticks(items):
    """items: [(x%, label)]. Every label is centred on its own tick — the end ones
    overflow into the axis gutter / the card's padding rather than being clamped to
    the plot edge, which would shift them into their neighbour."""
    return "".join(f'<span class="pf-xt" style="left:{_n(x)}%">{label}</span>'
                   for x, label in items)


def _pf_chart(plot, yticks="", xticks="", legend="", aria="", cls="", ycol=5, rcol=0):
    """The chart frame: a grid of [y-axis | plot | legend] over [_ | x-axis].

    ycol/rcol are widths in mono characters, so the axis gutter follows the tick
    text at whatever size the breakpoint renders it.
    """
    style = f"--pf-yc:{ycol}"
    if rcol:
        style += f";--pf-rc:{rcol}"
    aria_attr = f' role="group" aria-label="{esc(aria)}"' if aria else ""
    return (
        f'<div class="pf-chart{cls}" style="{style}"{aria_attr}>'
        f'<div class="pf-y">{yticks}</div>'
        f'<div class="pf-plot">{plot}<span class="pf-base"></span></div>'
        f'<div class="pf-x">{xticks}</div>'
        f'<div class="pf-leg">{legend}</div>'
        '</div>'
    )


def _spread(tops, gap):
    """Push overlapping direct labels apart, keeping their order and staying inside
    0-100%. tops is a list of (index, top%) sorted by top."""
    out = list(tops)
    for i in range(1, len(out)):
        if out[i][1] - out[i - 1][1] < gap:
            out[i] = (out[i][0], out[i - 1][1] + gap)
    overflow = out[-1][1] - 100 if out and out[-1][1] > 100 else 0
    if overflow:
        for i in range(len(out) - 1, -1, -1):
            out[i] = (out[i][0], out[i][1] - overflow)
            if i and out[i][1] - out[i - 1][1] >= gap:
                break
    return dict(out)


_ROLE_META = [
    ("primary", "Primary author"), ("postdoc", "Postdoc-led"),
    ("student", "Student-led"), ("significant", "Contributor"), ("other", "Other"),
]


def _nice_ticks(maxv, target=4):
    if maxv <= 0:
        return [0, 1]
    raw = maxv / target
    mag = 10 ** math.floor(math.log10(raw))
    step = next((mag * m for m in (1, 2, 2.5, 5, 10) if mag * m >= raw), mag * 10)
    step = max(1, int(round(step)))
    return list(range(0, math.ceil(maxv) + step, step))


def _roles_svg(pubs):
    """Publications per year, stacked by my authorship role.

    The five roles are not research areas, so they take a neutral lightness ramp
    (--role-*) plus a per-role hatch: the stack still separates in greyscale and
    the legend swatches carry the same fill+hatch, so nothing is keyed by colour
    alone (audit A2/A3). Each year is one focusable hit target.
    """
    from collections import defaultdict, Counter
    by_year = defaultdict(Counter)
    for p in pubs:
        y = p.get("year")
        if y:
            by_year[int(y)][p.get("authorshipCategory") or "other"] += 1
    if not by_year:
        return ""
    years = list(range(min(by_year), max(by_year) + 1))
    maxstack = max((sum(by_year[y].values()) for y in years), default=1)
    # Headroom is a fixed 12%, and gridlines above the data are dropped, so a bar
    # chart never sits in the bottom two thirds of its own plot.
    ticks = _nice_ticks(maxstack, 5)
    scale = maxstack * 1.12
    ticks = [t for t in ticks if t <= scale]
    n = len(years)
    slot = 100 / n
    yp = lambda v: (1 - v / scale) * 100

    plot = [_pf_grid(ticks, yp)]
    for i, y in enumerate(years):
        col = by_year[y]
        total = sum(col.values())
        left = i * slot + slot * 0.18
        width = slot * 0.64
        if total:
            segs = "".join(
                f'<i class="pf-seg seg-{key}" style="height:{_n(col[key] / total * 100)}%"></i>'
                for key, _ in _ROLE_META if col.get(key)
            )
            plot.append(f'<span class="pf-bar" style="left:{_n(left)}%;width:{_n(width)}%;'
                        f'height:{_n(100 - yp(total))}%">{segs}</span>')
            parts = ", ".join(f"{col[k]} {lab.lower()}" for k, lab in _ROLE_META if col.get(k))
            summ = f"{y}: {total} publication" + ("s" if total != 1 else "") + f" — {parts}"
            plot.append(f'<span class="pf-col" style="left:{_n(i * slot)}%;width:{_n(slot)}%" '
                        f'{_tip(summ)}></span>')
    xt = [(i * slot + slot / 2, str(y)) for i, y in enumerate(years) if y % 2 == 0]
    legend = "".join(f'<span class="pf-key"><i class="pf-kw seg-{key}"></i>{label}</span>'
                     for key, label in _ROLE_META)
    return _pf_chart("".join(plot), _pf_yticks(ticks, yp), _pf_xticks(xt),
                     legend=legend, ycol=3,
                     aria="Publications per year by my authorship role")


def _citations_svg(metrics):
    """Citations received per year — one cat-ic series on a linear scale, with the
    latest complete year lit as an energy star and labelled directly, so the peak
    is read off the mark rather than off a legend."""
    cpy = {int(y): v for y, v in (metrics.get("citationsPerYear") or {}).items()}
    if not cpy:
        return ""
    cur = max(cpy)
    years = [y for y in sorted(cpy) if y < cur] or sorted(cpy)
    vmax = max(cpy[y] for y in years)
    ticks = [t for t in _nice_ticks(vmax, 5) if t <= vmax * 1.12]
    scale = vmax * 1.12
    n = len(years)
    xp = lambda i: (i / (n - 1) * 100) if n > 1 else 50
    yp = lambda v: (1 - v / scale) * 100
    pts = [(xp(i), yp(cpy[y])) for i, y in enumerate(years)]

    line = " ".join(f"{'M' if i == 0 else 'L'}{_n(x)},{_n(y)}" for i, (x, y) in enumerate(pts))
    area = f"M{_n(pts[0][0])},100 " + " ".join(f"L{_n(x)},{_n(y)}" for x, y in pts) + \
           f" L{_n(pts[-1][0])},100 Z"
    plot = [_pf_grid(ticks, yp),
            '<svg class="pf-geo" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">'
            f'<path class="pf-area" d="{area}"/>'
            f'<path class="pf-cit-line" d="{line}" vector-effect="non-scaling-stroke"/>'
            '</svg>']
    for x, y in pts[:-1]:
        plot.append(f'<span class="pf-pt" style="left:{_n(x)}%;top:{_n(y)}%"></span>')
    lx, ly = pts[-1]
    plot.append(f'<svg class="pf-star" style="left:{_n(lx)}%;top:{_n(ly)}%" aria-hidden="true" '
                'focusable="false"><use href="#star4"/></svg>')
    plot.append(f'<span class="pf-dl" style="right:2px;top:{_n(ly)}%">'
                f'{cpy[years[-1]]:,} in {years[-1]}</span>')
    step = 100 / (n - 1) if n > 1 else 100
    for i, y in enumerate(years):
        left = max(0, xp(i) - step / 2)
        plot.append(f'<span class="pf-band" style="left:{_n(left)}%;'
                    f'width:{_n(min(step, 100 - left))}%" {_tip(f"{y}: {cpy[y]:,} citations")}></span>')
    xt = [(xp(i), str(y)) for i, y in enumerate(years) if y % 2 == 0]
    return _pf_chart("".join(plot), _pf_yticks(ticks, yp), _pf_xticks(xt), ycol=5,
                     aria="Citations received per year")


# RIQ series: (key, right-edge label). The typical-range band bounds (audit A14).
_RIQ_SERIES = [
    ("all", "All papers"), ("primary", "Primary"),
    ("significant", "Contributor"), ("student", "Student-led"), ("postdoc", "Postdoc-led"),
]
_RIQ_BAND = (60, 150)


def _riq_svg(metrics):
    """RIQ over time by authorship role. Five series in the neutral role ramp, each
    with its own dash pattern and a direct label at the right edge carrying its last
    plotted value — no swatch legend, and the typical-range band prints its bounds."""
    riq = metrics.get("riqByCategory") or {}
    data = {}
    for key, _ in _RIQ_SERIES:
        ser = (riq.get(key) or {}).get("riq_series") or {}
        pts = sorted((int(y), float(v)) for y, v in ser.items())
        if pts:
            c = max(y for y, _ in pts)
            pts = [(y, v) for y, v in pts if y < c]
        data[key] = pts
    years = sorted({y for pts in data.values() for y, _ in pts})
    if not years:
        return ""
    vmax = max((v for pts in data.values() for _, v in pts), default=1)
    ticks = [t for t in _nice_ticks(vmax, 5) if t <= vmax * 1.12]
    scale = vmax * 1.12
    y0, y1 = years[0], years[-1]
    xp = lambda yr: ((yr - y0) / (y1 - y0) * 100) if y1 > y0 else 50
    yp = lambda v: (1 - v / scale) * 100

    lo, hi = _RIQ_BAND
    plot = [f'<span class="pf-band-typ" style="top:{_n(yp(hi))}%;height:{_n(yp(lo) - yp(hi))}%">'
            f'<i>Typical range {lo}–{hi}</i></span>',
            f'<span class="pf-mean" style="top:{_n(yp(100))}%"></span>',
            _pf_grid(ticks, yp)]
    paths = []
    for key, _ in _RIQ_SERIES:
        pts = data[key]
        if len(pts) < 2:
            continue
        d = " ".join(f"{'M' if i == 0 else 'L'}{_n(xp(yr))},{_n(yp(v))}"
                     for i, (yr, v) in enumerate(pts))
        paths.append(f'<path class="pf-ln ln-{key}" d="{d}" vector-effect="non-scaling-stroke"/>')
    plot.append('<svg class="pf-geo" viewBox="0 0 100 100" preserveAspectRatio="none" '
                f'aria-hidden="true">{"".join(paths)}</svg>')
    step = 100 / (len(years) - 1) if len(years) > 1 else 100
    for yr in years:
        bits = [f"{label} {round(dict(data[key])[yr])}"
                for key, label in _RIQ_SERIES if yr in dict(data[key])]
        if not bits:
            continue
        left = max(0, xp(yr) - step / 2)
        plot.append(f'<span class="pf-band" style="left:{_n(left)}%;width:{_n(min(step, 100 - left))}%" '
                    f'{_tip(f"{yr} — " + " · ".join(bits))}></span>')
    xt = [(xp(yr), str(yr)) for yr in years if yr % 2 == 0]

    # direct labels at the right edge, nudged apart so no two overlap
    ends = [(key, label, data[key][-1][1]) for key, label in _RIQ_SERIES if data[key]]
    order = sorted(range(len(ends)), key=lambda i: yp(ends[i][2]))
    spread = _spread([(i, yp(ends[i][2])) for i in order], 8.0)
    legend = "".join(
        f'<span class="pf-rl ln-{ends[i][0]}" style="--y:{_n(spread[i])}%">'
        f'<b>{round(ends[i][2]):,}</b> {ends[i][1]}</span>'
        for i in range(len(ends))
    )
    rcol = max(len(f"{round(v):,} {label}") for _, label, v in ends) + 2
    return _pf_chart("".join(plot), _pf_yticks(ticks, yp), _pf_xticks(xt), legend=legend,
                     cls=" has-r", ycol=3, rcol=rcol,
                     aria="Research Impact Quotient over time by authorship role")


def _mix_svg(pubs):
    """Research mix: one hard-segmented 100% bar, each share labelled INSIDE its own
    segment (the old detached legend put "Interpretability 21%" inside the Discovery
    segment — audit A12). Shares come from percent_shares(), so they total 100."""
    from collections import defaultdict
    # (full name, key, short label)
    areas = [("Statistical Learning & AI", "sla", "Stat. learning"),
             ("Interpretability & Insight", "ii", "Interpretability"),
             ("Inference & Computation", "ic", "Inference"),
             ("Discovery & Understanding", "du", "Discovery")]
    agg = defaultdict(float)
    for p in pubs:
        cp = p.get("categoryProbabilities") or {}
        tot = sum(float(cp.get(name, 0)) for name, _, _ in areas)
        if tot <= 0:
            continue
        for name, _, _ in areas:
            agg[name] += float(cp.get(name, 0)) / tot
    grand = sum(agg.values())
    if grand <= 0:
        return ""
    fr = sorted(((key, name, short, agg[name] / grand) for name, key, short in areas),
                key=lambda r: -r[3])
    pcts = percent_shares([row[3] for row in fr])

    segs, keys = [], []
    for (key, name, short, _frac), pct in zip(fr, pcts):
        tip = f"{name}: {pct}% of classified output"
        # Below ~10% a segment is too narrow to hold its own name; it keeps the
        # percentage inside and leans on the key line for the area.
        inner = (f'<b>{esc(short)}</b><i>{pct}%</i>' if pct >= 10 else f'<i>{pct}%</i>')
        segs.append(f'<span class="mix-seg mix-{key}" style="flex:{pct}" {_tip(tip)}>{inner}</span>')
        keys.append(f'<span class="pf-key"><i class="pf-kw mix-{key}"></i>{esc(short)} {pct}%</span>')
    total_txt = ", ".join(f"{short} {pct}%" for (_k, _n_, short, _f), pct in zip(fr, pcts))
    return (f'<div class="pf-mix" role="group" aria-label="Research mix: {esc(total_txt)}">'
            f'{"".join(segs)}</div>'
            f'<div class="pf-leg pf-leg-mix" aria-hidden="true">{"".join(keys)}</div>')


# Authorship dashboard tiles: (role key in publications_data + content.json libraries, label)
_ADS_LIB = "https://ui.adsabs.harvard.edu/user/libraries/"
_ADS_LIBRARY_TILES = [
    ("total", "Total papers"), ("primary", "Primary author"), ("postdoc", "Postdoc-led"),
    ("student", "Student-led"), ("significant", "Contributor"),
]


def generate_publications_redesign(data):
    """Generate the inner HTML for #publications-content (redesign).

    Reads publications_data.json directly and emits the dashboard, controls,
    filter chips, and all paper cards pre-sorted newest-first then most-cited.
    """
    try:
        pub_data = json.loads(PUBLICATIONS_JSON.read_text(encoding="utf-8"))
    except (OSError, ValueError) as err:
        raise BuildError(f"cannot read {PUBLICATIONS_JSON.name}: {err}") from err
    metrics = pub_data.get("metrics", {})
    pubs = pub_data.get("publications", [])

    total_papers = metrics.get("totalPapers", len(pubs))
    total_citations = metrics.get("totalCitations", 0)

    # Per-category chip counts: one bucket per paper (its argmax area), so the four
    # chips partition the corpus and each count is exactly the number of cards that
    # chip reveals.
    cat_counts = {"sla": 0, "ii": 0, "ic": 0, "du": 0}
    papers_with_year = []
    for p in pubs:
        if not p.get("year"):
            continue
        papers_with_year.append(p)
        cat_counts[_pub_cat_key(p)] += 1

    all_count = len(papers_with_year)
    if len(pubs) != all_count:
        warn(f"{len(pubs) - all_count} publication(s) have no year and are omitted from "
             f"the cards, chips and figures (role tiles still count them)")

    # Pre-sort: newest year first, then most cited
    papers_with_year.sort(
        key=lambda p: (-int(p.get("year", 0) or 0), -int(p.get("citations", 0) or 0))
    )

    cards = "".join(_generate_paper_card(p) for p in papers_with_year)

    # Top summary: authorship-role buttons linking to the curated ADS libraries
    from collections import Counter
    role_counts = Counter(p.get("authorshipCategory") for p in pubs)
    libraries = (data.get("sections", {}).get("publications", {}) or {}).get("libraries", {}) or {}
    role_buttons = [(label, total_papers if key == "total" else role_counts.get(key, 0),
                     libraries.get(key, ""))
                    for key, label in _ADS_LIBRARY_TILES if libraries.get(key)]
    if len(role_buttons) != len(_ADS_LIBRARY_TILES):
        warn("sections.publications.libraries is missing an ADS library id; "
             "the authorship dashboard is incomplete")
    # The four role tiles are curated ADS libraries and do not cover every paper, so
    # say so underneath rather than letting five tiles read as a partition (D7).
    covered = sum(role_counts.get(key, 0) for key, _ in _ADS_LIBRARY_TILES if key != "total")
    coverage_html = ""
    if 0 < covered < total_papers:
        coverage_html = (
            f'<p class="pub-stats-note">{covered} of {total_papers} papers sit in one of '
            'these curated ADS libraries; the rest are co-authored work, counted in the '
            'total and shown as “Other” in the roles figure below.</p>')
    dashboard = '<div class="pub-stats pub-authorship" data-chip>' + "".join(
        f'<a class="pub-stat pub-statlink" href="{url_attr(_ADS_LIB + lib)}" target="_blank" rel="noopener" '
        f'aria-label="{label}: {cnt} papers (opens the ADS library)">'
        f'<span class="n">{cnt:,}</span><span class="l">{label}</span>'
        f'<span class="pub-stat-go" aria-hidden="true">ADS ↗</span></a>'
        for label, cnt, lib in role_buttons
    ) + '</div>' + coverage_html

    # Aggregate author-profile links (ADS search · Google Scholar · ORCID) from content.json
    plinks = (data.get("sections", {}).get("publications", {}) or {}).get("links", {}) or {}
    prof_defs = [("ADS", plinks.get("ads")), ("Google Scholar", plinks.get("scholar")),
                 ("ORCID", plinks.get("orcid"))]
    prof_links = "".join(
        f'<a class="reslink" href="{url_attr(u)}" target="_blank" rel="noopener">{lbl} ↗</a>'
        for lbl, u in prof_defs if u
    )
    # Every record as BibTeX. The file is generated from this same cache by
    # scripts/export_bib.py and `npm run check` fails when it drifts (C12).
    prof_links += (f'<a class="reslink" href="{BIBTEX_PATH}" download>BibTeX ↓</a>')
    profiles = (
        '<div class="pub-profiles"><span class="pub-profiles-label">Full author profiles</span>'
        f'{prof_links}</div>'
    ) if prof_links else ""
    cpy = {int(y): v for y, v in metrics.get("citationsPerYear", {}).items()}
    # The peak is a direct label on the mark now, and the scale is plain linear, so the
    # head carries only the total, its provenance and the year the chart leaves out.
    peak_txt = f"{total_citations:,} total · ADS + Google Scholar"
    if cpy:
        peak_txt += f" · {max(cpy)} partial, omitted"

    def _fig(title, meta, svg, wide=False):
        cls = "pub-fig wide" if wide else "pub-fig"
        return (
            f'<figure class="{cls}" data-chip>'
            f'<figcaption class="pub-fig-head"><span class="t">{title}</span>'
            f'<span class="m">{meta}</span></figcaption>'
            f'{svg}</figure>'
        )

    figures = (
        '<div class="pub-figures">'
        + _fig("Research mix", "share of work by area", _mix_svg(papers_with_year), wide=True)
        + _fig("Citations received per year", peak_txt, _citations_svg(metrics), wide=True)
        + _fig("Publications by year &amp; role", "hover or tab through the bars", _roles_svg(papers_with_year))
        + _fig("Research impact by role", "RIQ vs. the typical astronomer range", _riq_svg(metrics))
        + '</div>'
        '<p class="pub-fig-note"><strong>Why these figures?</strong> I find it easier to see what I work on '
        'and the impact it’s had as a picture than as a list — so rather than just enumerate papers, these '
        'summarize the record a few ways. <strong>Research '
        'mix</strong> shows what the work is about, weighting each paper by its classification across the four '
        'areas. The <strong>role breakdowns</strong> separate work led as primary author from work led by '
        'postdocs, students, and larger collaborations — each with its own shade and hatch, so they '
        'separate without relying on colour. <strong>RIQ</strong> '
        '(Research Impact Quotient) normalizes citation impact by career length — roughly √(total citations) ÷ '
        'years active — so impact compares fairly across career stages instead of just growing with time; the '
        'shaded band is the 60–150 typical range for established astronomers '
        '(<a href="https://doi.org/10.1371/journal.pone.0046428" target="_blank" rel="noopener">Pepe &amp; Kurtz 2012</a>).</p>'
    )

    # Featured spotlight (papers flagged featured=true), shown with abstracts
    featured = [p for p in papers_with_year if p.get("featured")]
    feat_html = ""
    if featured:
        fcards = "".join(_generate_paper_card(p, board=True) for p in featured)
        feat_html = (
            '<section class="pub-featured" data-lv-pinned data-chip aria-labelledby="featured-head">'
            '<h2 id="featured-head" class="pub-featured-head">Featured work</h2>'
            f'<div class="featured-grid">{fcards}</div>'
            '</section>'
        )

    chips = "".join(
        f'<button class="chip" data-cat="{key}" aria-pressed="false">'
        f'<span class="dot d-{key}"></span>{_PUB_CAT_LABEL[key]} '
        f'<span class="ct">{cat_counts[key]}</span></button>'
        for key in ("du", "ic", "sla", "ii")
    )
    controls = (
        '<div class="pub-controls">'
        '<input type="search" id="pub-search" class="pub-search" data-lv-search '
        'placeholder="Search title or author…" aria-label="Search publications">'
        '<select id="pub-sort" class="pub-sort" data-lv-sort-control aria-label="Sort publications">'
        '<option value="year">Newest first</option>'
        '<option value="num">Most cited</option></select>'
        '<div class="pub-filters" id="pub-filters" data-lv-filters role="group" '
        'aria-label="Filter by research area">'
        f'<button class="chip is-active" data-cat="all" aria-pressed="true">'
        f'All <span class="ct">{all_count}</span></button>'
        f'{chips}'
        '</div>'
        '</div>'
    )

    list_section = (
        f'<div id="pub-list" class="pub-list" data-lv-list data-chip>{cards}</div>'
        '<p id="pub-empty" class="pub-empty" data-lv-empty hidden>'
        'No papers match your search/filters. '
        '<button type="button" class="linkbtn" id="pub-reset" data-lv-reset>Show all</button></p>'
        '<div class="pub-loadmore-wrap">'
        '<button type="button" id="pub-loadmore" class="btn-ghost" data-lv-more>Load more</button></div>'
    )

    # #pub-root is the listview root: everything listview.js shows/hides lives inside
    # it, including the pinned Featured board.
    return (
        '<div class="container">'
        + dashboard
        + profiles
        + figures
        + '<div id="pub-root" data-listview data-lv-batch="20" data-lv-sort="year">'
        + feat_html
        + '<h2 class="sr-only">All publications</h2>'
        + controls
        + listview_status()
        + list_section
        + '</div></div>'
    )


# ---------------------------------------------------------------------------
# Page assembly + entry point
# ---------------------------------------------------------------------------

_CONTENT_GENERATORS = {
    "publications": generate_publications_redesign,
    "biography": generate_biography,
    "awards": gen_awards,
    "service": gen_service,
    "talks": gen_talks,
    "teaching": gen_teaching,
    "mentorship": gen_mentorship,
    "software": gen_software,
    "news": gen_news,
}

# Home is four generated <section>s rather than one content container.
_HOME_SECTIONS = [
    ("team", "section", generate_home_team),
    ("about", "section", generate_home_about),
    ("research", "section", generate_home_research),
    ("join", "section", generate_home_collab),
]


def build_page(key, data):
    """Render one complete page: generate its content, then wrap it in the shell."""
    if key == "index":
        content = [(sec_id, cls, gen(data)) for sec_id, cls, gen in _HOME_SECTIONS]
    elif key in _CONTENT_GENERATORS:
        content = _CONTENT_GENERATORS[key](data)
    else:
        content = ""            # 404: the shell supplies the whole body
    return render_shell(key, data, content)


def main():
    """Render every registered page (plus sitemap.xml) from the data files."""
    print(f"Loading content from {CONTENT_JSON}...")
    if not CONTENT_JSON.exists():
        print(f"ERROR: {CONTENT_JSON} not found", file=sys.stderr)
        sys.exit(1)

    data = json.loads(CONTENT_JSON.read_text(encoding="utf-8"))

    failures = 0
    for key, page in PAGES.items():
        path = PROJECT_ROOT / page["file"]
        print(f"  Rendering {page['file']}...")
        try:
            html = build_page(key, data)
        except (BuildError, KeyError, OSError, TypeError, ValueError) as err:
            # One bad data file must not block the other pages.
            print(f"    ERROR: {page['file']} not rendered: {type(err).__name__}: {err}",
                  file=sys.stderr)
            failures += 1
            continue
        if not path.exists() or path.read_text(encoding="utf-8") != html:
            path.write_text(html, encoding="utf-8")
            print(f"    -> Updated {page['file']}")
        else:
            print(f"    -> No changes needed for {page['file']}")

    write_sitemap()
    write_feed(data)

    if failures:
        print(f"Done with {failures} page(s) failing. See the errors above.", file=sys.stderr)
        sys.exit(1)
    print("Done! Every page has been rendered from assets/data/.")


if __name__ == "__main__":
    main()
